---
# tasks file for setup_postgres

# Install PostgreSQL server and client
- name: Install PostgreSQL
  yum:
    name: 
      - postgresql-server
      - postgresql
    state: present

- name: Initialize DB
  command: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Start and enable PostgreSQL 
  service:
    name: postgresql
    state: started
    enabled: yes

# Create database user for Node.js/Flask app
- name: Create devops user with password
  become_user: postgres
  postgresql_user:
    name: devops
    password: password
    state: present

# Copy the schema.sql file from Ansible control machine to the target server
- name: Copy schema.sql to target server
  copy:
    src: files/schema.sql    
    dest: /tmp/schema.sql     
    owner: postgres
    group: postgres

# Check if database already exists
- name: Check if sharedappdb already exists
  become_user: postgres
  command: psql -tAc "SELECT 1 FROM pg_database WHERE datname='sharedappdb'"
  register: db_exists
  failed_when: false
  changed_when: false

# Run the SQL
- name: Apply schema.sql to create sharedappdb
  become_user: postgres
  shell: psql -f /tmp/schema.sql
  when: db_exists.stdout != "1"

...